[forest]
"plants@append" = [
    {weight=0.007, block="base_survival:mushroom"},
    {weight=0.01, block="base_survival:small_rock"}
]

[plains]
"plants@append" = [
    {weight=0.007, block="base_survival:small_rock"}
]
